export const Events = {

  ANSWER_SUBMITTED: "ANSWER_SUBMITTED",

  REVIEW_UPDATED: "REVIEW_UPDATED",

  SESSION_STARTED: "SESSION_STARTED",

  SESSION_FINISHED: "SESSION_FINISHED",

  BACKUP_REQUESTED: "BACKUP_REQUESTED"

}